name: Continuous Integration and Deployment

on:
  push:
    branches: "main"

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.2"
      - uses: actions/checkout@v3
      
      - name: Clear Config and Cache
        run: |
          php artisan route:clear
          php artisan route:clear
          php artisan view:clear
      - name: Set Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Deploy to Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /
          dangerous-clean-slate: false
